version: '3.0'
services:
  db:
    image: mysql:5.7
    restart: on-failure:10
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "33061:3306"

  backend:
    image: tomcat:8
    restart: on-failure:10
    ports:
      - "8088:8080"
    volumes:
      - ./PMQ.war:/usr/local/tomcat/webapps/PMQ.war
    depends_on:
      - "db"
    environment:
      DB_HOST: db
    entrypoint:
      - "catalina.sh"
      - "run"
  nginx:
    image: nginx:1.16
    restart: on-failure:10
    ports:
      - "8001:8001"
    depends_on:
      - "backend"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/srv/PMQ/static
      